@workspace = emrearmaganxx
@repo_slug = atlas

### Get me
GET https://api.bitbucket.org/2.0/user
Authorization: Basic {{BITBUCKET_USER}}:{{BITBUCKET_TOKEN}}
Content-Type: application/json
Accept: application/json

### Get repository details
GET https://api.bitbucket.org/2.0/repositories/{{workspace}}/{{repo_slug}}
Authorization: Basic {{BITBUCKET_USER}}:{{BITBUCKET_TOKEN}}
Content-Type: application/json
Accept: application/json

> {%
  const mainBranch = response.body?.mainbranch?.name;
  if (mainBranch) {
    client.global.set("bitbucket_main_branch", String(mainBranch));
  }
%}

### README candidate
GET https://api.bitbucket.org/2.0/repositories/{{workspace}}/{{repo_slug}}/src/{{bitbucket_main_branch}}/README.md
Authorization: Basic {{BITBUCKET_USER}}:{{BITBUCKET_TOKEN}}
Content-Type: application/json
Accept: text/plain

### Get open pull requests
GET https://api.bitbucket.org/2.0/repositories/{{workspace}}/{{repo_slug}}/pullrequests?state=OPEN&pagelen=50
Authorization: Basic {{BITBUCKET_USER}}:{{BITBUCKET_TOKEN}}
Content-Type: application/json
Accept: application/json

> {%
  const pr = response.body?.values?.[0];
  if (!pr) throw new Error("No OPEN pull requests found");
  const prId = pr.id;
  const sourceHash = pr.source?.commit?.hash;
  const destinationHash = pr.destination?.commit?.hash; 
  if (!prId) throw new Error("PR id missing");
  if (!sourceHash) throw new Error("Source commit hash missing");
  client.global.set("bitbucket_pr_id", String(prId));
  client.global.set("bitbucket_commit_hash", String(sourceHash));
  client.global.set("bitbucket_source_commit_hash", String(sourceHash));
  if (destinationHash) {
    client.global.set("bitbucket_destination_commit_hash", String(destinationHash));
  }
%}

### Get pull request details
GET https://api.bitbucket.org/2.0/repositories/{{workspace}}/{{repo_slug}}/pullrequests/2
Authorization: Basic {{BITBUCKET_USER}}:{{BITBUCKET_TOKEN}}
Content-Type: application/json
Accept: application/json

> {%
 const pr = response.body;

  const diffstatUrl = pr?.links?.diffstat?.href;
  const diffUrl = pr?.links?.diff?.href;

  if (!diffstatUrl) throw new Error("diffstat URL missing");
  if (!diffUrl) throw new Error("diff URL missing");

  client.global.set("bitbucket_diffstat_url", diffstatUrl);
  client.global.set("bitbucket_diff_url", diffUrl);
%}


### Get pull request comments
GET https://api.bitbucket.org/2.0/repositories/{{workspace}}/{{repo_slug}}/pullrequests/{{bitbucket_pr_id}}/comments
Authorization: Basic {{BITBUCKET_USER}}:{{BITBUCKET_TOKEN}}
Content-Type: application/json
Accept: application/json


### Get commits
GET https://api.bitbucket.org/2.0/repositories/{{workspace}}/{{repo_slug}}/commits
Authorization: Basic {{BITBUCKET_USER}}:{{BITBUCKET_TOKEN}}
Content-Type: application/json
Accept: application/json


### Diff stats (dynamic from PR)
GET {{bitbucket_diffstat_url}}
Authorization: Basic {{BITBUCKET_USER}}:{{BITBUCKET_TOKEN}}
Content-Type: application/json
Accept: application/json

### Diff (dynamic from PR)
GET {{bitbucket_diff_url}}
Authorization: Basic {{BITBUCKET_USER}}:{{BITBUCKET_TOKEN}}
Content-Type: application/json
Accept: application/json

### List activity
GET https://api.bitbucket.org/2.0/repositories/{{ workspace }}/{{ repo_slug }}/pullrequests/{{ bitbucket_pr_id }}/activity
Authorization: Basic {{BITBUCKET_USER}}:{{BITBUCKET_TOKEN}}
Content-Type: application/json
Accept: application/json


