@workspace = emrearmaganxx
@repo_slug = atlas

### Get me
GET https://api.bitbucket.org/2.0/user
Authorization: Basic {{BITBUCKET_USER}}:{{BITBUCKET_TOKEN}}
Content-Type: application/json
Accept: application/json

### Get repository details
GET https://api.bitbucket.org/2.0/repositories/{{workspace}}/{{repo_slug}}
Authorization: Basic {{BITBUCKET_USER}}:{{BITBUCKET_TOKEN}}
Content-Type: application/json
Accept: application/json

### Get open pull requests
GET https://api.bitbucket.org/2.0/repositories/{{workspace}}/{{repo_slug}}/pullrequests?state=OPEN&pagelen=50
Authorization: Basic {{BITBUCKET_USER}}:{{BITBUCKET_TOKEN}}
Content-Type: application/json
Accept: application/json

> {%
  const pr = response.body?.values?.[0];
  if (!pr) throw new Error("No OPEN pull requests found");
  const prId = pr.id;
  const sourceHash = pr.source?.commit?.hash;
  const destinationHash = pr.destination?.commit?.hash; 
  if (!prId) throw new Error("PR id missing");
  if (!sourceHash) throw new Error("Source commit hash missing");
  client.global.set("bitbucket_pr_id", String(prId));
  client.global.set("bitbucket_commit_hash", String(sourceHash));
  client.global.set("bitbucket_source_commit_hash", String(sourceHash));
  if (destinationHash) {
    client.global.set("bitbucket_destination_commit_hash", String(destinationHash));
  }
%}


### Get pull request details
GET https://api.bitbucket.org/2.0/repositories/{{workspace}}/{{repo_slug}}/pullrequests/{{bitbucket_pr_id}}
Authorization: Basic {{BITBUCKET_USER}}:{{BITBUCKET_TOKEN}}
Content-Type: application/json
Accept: application/json

### Get pull request comments
GET https://api.bitbucket.org/2.0/repositories/{{workspace}}/{{repo_slug}}/pullrequests/{{bitbucket_pr_id}}/comments
Authorization: Basic {{BITBUCKET_USER}}:{{BITBUCKET_TOKEN}}
Content-Type: application/json
Accept: application/json

### Get build statuses for commit
GET https://api.bitbucket.org/2.0/repositories/{{workspace}}/{{repo_slug}}/pullrequests/{{bitbucket_pr_id}}/statuses
Authorization: Basic {{BITBUCKET_USER}}:{{BITBUCKET_TOKEN}}
Content-Type: application/json
Accept: application/json

### Diff (copy from above repos)
GET https://api.bitbucket.org/2.0/repositories/emrearmaganxx/atlas/diff/emrearmaganxx/atlas:9b6ec2c8e700%0De52b01460769?from_pullrequest_id=1&topic=true
Authorization: Basic {{BITBUCKET_USER}}:{{BITBUCKET_TOKEN}}
Content-Type: application/json
Accept: application/json


### Diff stats (copy from above repos)
GET https://api.bitbucket.org/2.0/repositories/emrearmaganxx/atlas/diffstat/emrearmaganxx/atlas:9b6ec2c8e700%0De52b01460769?from_pullrequest_id=1&topic=true
Authorization: Basic {{BITBUCKET_USER}}:{{BITBUCKET_TOKEN}}
Content-Type: application/json
Accept: application/json
