--------------------------------------------------------------------------------
-- Current User
--------------------------------------------------------------------------------
---@class JiraUser
---@field account_id string
---@field display_name string
---@field email string

--------------------------------------------------------------------------------
-- Comments
--------------------------------------------------------------------------------
---@class JiraComment
---@field id string
---@field self string|nil
---@field author JiraUser|nil
---@field body string
---@field _body table|nil -- raw adf
---@field created string|nil
---@field updated string|nil
---@field parent_id string|number|nil
---@field jsd_public boolean|nil
---@field children JiraComment[]|nil

---@class JiraCommentPage
---@field start_at number
---@field total number
---@field comments JiraComment[]

--------------------------------------------------------------------------------
-- Issue
--------------------------------------------------------------------------------
---@class JiraIssueType
---@field id string
---@field name string
---@field description string|nil
---@field subtask boolean
---@field entity_id string|nil

---@class JiraProject
---@field id string
---@field key string
---@field name string
---@field self string

---@class JiraIssue
---@field key string
---@field summary string
---@field project JiraProject|nil
---@field status string|nil
---@field status_id string|nil
---@field status_category string|nil
---@field status_color string|nil
---@field type JiraIssueType|nil
---@field priority string|nil
---@field assignee JiraUser|nil
---@field reporter string|nil
---@field story_points number|nil
---@field approvers string[]|nil
---@field duedate string|nil
---@field parent JiraIssue|nil
---@field children JiraIssue[]|nil

--------------------------------------------------------------------------------
-- Issue Transitions
--------------------------------------------------------------------------------
---@class JiraIssueTransition
---@field id string
---@field name string
---@field to_status_id string|nil
---@field to_status_name string|nil
---@field to_status_category string|nil
---@field to_status_color string|nil

---@class JiraIssueTransitionPage
---@field transitions JiraIssueTransition[]

--------------------------------------------------------------------------------
-- Issue History
--------------------------------------------------------------------------------
---@alias JiraIssueHistoryField
---| "issuetype"
---| "priority"
---| "timeoriginalestimate"
---| "timeestimate"
---| "status"
---| "Rank"
---| "timespent"
---| "WorklogId"
---| "Comment"
---| "assignee"
---| "description"
---| "IssueParentAssociation"

---@class JiraIssueHistoryItem
---@field field JiraIssueHistoryField|nil
---@field field_type string|nil
---@field from string|nil
---@field from_string string|nil
---@field to string|nil
---@field to_string string|nil

---@class JiraIssueHistoryEntry
---@field id string
---@field created string|nil
---@field author JiraUser|nil
---@field items JiraIssueHistoryItem[]

---@class JiraIssueHistoryPage
---@field self string|nil
---@field start_at number
---@field max_results number
---@field total number
---@field is_last boolean
---@field values JiraIssueHistoryEntry[]
