---@class JiraCurrentUser
---@field account_id string
---@field display_name string
---@field email string

---@class JiraIssue
---@field key string
---@field summary string
---@field status string
---@field status_category string
---@field status_color string|nil
---@field type string
---@field priority string
---@field assignee string
---@field reporter string
---@field duedate string|nil
---@field subtask boolean
---@field parent JiraIssue|nil
---@field children JiraIssue[]|nil
