@jira_api_version = 3
@jira_issue_key = KAN-1
@jira_project_key = KAN
@jira_transition_id = 31
@jira_account_id = 60129fc6a7fb40006900d080
@jira_comment_id = 10001

### Get current user
GET {{JIRA_BASE_URL}}/rest/api/{{jira_api_version}}/myself
Authorization: Basic {{JIRA_EMAIL}}:{{JIRA_TOKEN}}
Accept: application/json
Content-Type: application/json

### Search issues (v3)
POST {{JIRA_BASE_URL}}/rest/api/{{jira_api_version}}/search/jql
Authorization: Basic {{JIRA_EMAIL}}:{{JIRA_TOKEN}}
Content-Type: application/json
Accept: application/json

{
  "jql": "project = {{jira_project_key}} ORDER BY updated DESC",
  "fields": ["summary", "status", "assignee"],
  "nextPageToken": "",
  "maxResults": 10
}


### Get transitions
GET {{JIRA_BASE_URL}}/rest/api/{{jira_api_version}}/issue/{{jira_issue_key}}/transitions
Authorization: Basic {{JIRA_EMAIL}}:{{JIRA_TOKEN}}
Accept: application/json


### Transition issue
POST {{JIRA_BASE_URL}}/rest/api/{{jira_api_version}}/issue/{{jira_issue_key}}/transitions
Authorization: Basic {{JIRA_EMAIL}}:{{JIRA_TOKEN}}
Content-Type: application/json
Accept: application/json

{
  "transition": {
    "id": "{{jira_transition_id}}"
  }
}


### Add worklog
POST {{JIRA_BASE_URL}}/rest/api/{{jira_api_version}}/issue/{{jira_issue_key}}/worklog
Authorization: Basic {{JIRA_EMAIL}}:{{JIRA_TOKEN}}
Content-Type: application/json
Accept: application/json

{
  "timeSpent": "1h",
  "comment": {
    "type": "doc",
    "version": 1,
    "content": [
      {
        "type": "paragraph",
        "content": [
          {
            "type": "text",
            "text": "Worked on implementation"
          }
        ]
      }
    ]
  }
}


### Assign issue
PUT {{JIRA_BASE_URL}}/rest/api/{{jira_api_version}}/issue/{{jira_issue_key}}/assignee
Authorization: Basic {{JIRA_EMAIL}}:{{JIRA_TOKEN}}
Content-Type: application/json
Accept: application/json

{
  "accountId": "{{jira_account_id}}"
}


### Get issue details
GET {{JIRA_BASE_URL}}/rest/api/{{jira_api_version}}/issue/{{jira_issue_key}}
Authorization: Basic {{JIRA_EMAIL}}:{{JIRA_TOKEN}}
Accept: application/json


### Get project statuses
GET {{JIRA_BASE_URL}}/rest/api/{{jira_api_version}}/project/{{jira_project_key}}/statuses
Authorization: Basic {{JIRA_EMAIL}}:{{JIRA_TOKEN}}
Accept: application/json


### Get comments
GET {{JIRA_BASE_URL}}/rest/api/{{jira_api_version}}/issue/{{jira_issue_key}}/comment
Authorization: Basic {{JIRA_EMAIL}}:{{JIRA_TOKEN}}
Accept: application/json


### Add comment
POST {{JIRA_BASE_URL}}/rest/api/{{jira_api_version}}/issue/{{jira_issue_key}}/comment
Authorization: Basic {{JIRA_EMAIL}}:{{JIRA_TOKEN}}
Content-Type: application/json
Accept: application/json

{
  "body": {
    "type": "doc",
    "version": 1,
    "content": [
      {
        "type": "paragraph",
        "content": [
          {
            "type": "text",
            "text": "This is a comment from atlas.nvim"
          }
        ]
      }
    ]
  }
}


### Edit comment
PUT {{JIRA_BASE_URL}}/rest/api/{{jira_api_version}}/issue/{{jira_issue_key}}/comment/{{jira_comment_id}}
Authorization: Basic {{JIRA_EMAIL}}:{{JIRA_TOKEN}}
Content-Type: application/json
Accept: application/json

{
  "body": {
    "type": "doc",
    "version": 1,
    "content": [
      {
        "type": "paragraph",
        "content": [
          {
            "type": "text",
            "text": "Updated comment text"
          }
        ]
      }
    ]
  }
}


### Update issue fields
PUT {{JIRA_BASE_URL}}/rest/api/{{jira_api_version}}/issue/{{jira_issue_key}}
Authorization: Basic {{JIRA_EMAIL}}:{{JIRA_TOKEN}}
Content-Type: application/json
Accept: application/json

{
  "fields": {
    "summary": "Updated summary from atlas.nvim"
  }
}


### Create issue
POST {{JIRA_BASE_URL}}/rest/api/{{jira_api_version}}/issue
Authorization: Basic {{JIRA_EMAIL}}:{{JIRA_TOKEN}}
Content-Type: application/json
Accept: application/json

{
  "fields": {
    "project": {
      "key": "{{jira_project_key}}"
    },
    "summary": "New issue from atlas.nvim",
    "issuetype": {
      "name": "Task"
    }
  }
}


### Get create metadata
GET {{JIRA_BASE_URL}}/rest/api/{{jira_api_version}}/issue/createmeta?projectKeys={{jira_project_key}}
Authorization: Basic {{JIRA_EMAIL}}:{{JIRA_TOKEN}}
Accept: application/json
